BEGIN;
--
-- Create model Classroom
--
CREATE TABLE "student_management_classroom" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "grade" integer NOT NULL, "section" varchar(10) NOT NULL, "room_number" varchar(10) NOT NULL);
--
-- Create model CollectorNode
--
CREATE TABLE "student_management_collectornode" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "floor_number" integer NULL, "mac_address" varchar(17) NOT NULL UNIQUE, "ip_address" inet NULL, "status" varchar(10) NOT NULL, "last_heartbeat" timestamp with time zone NULL, "remarks" text NULL);
--
-- Create model School
--
CREATE TABLE "student_management_school" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(255) NOT NULL UNIQUE, "slug" varchar(100) NOT NULL UNIQUE, "is_active" boolean NOT NULL);
--
-- Create model Student
--
CREATE TABLE "student_management_student" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "first_name" varchar(100) NOT NULL, "last_name" varchar(100) NOT NULL, "dob" date NOT NULL, "roll_number" integer NOT NULL, "is_fully_enrolled" boolean NOT NULL, "photo_url" varchar(200) NOT NULL, "gender" varchar(1) NOT NULL, "blood_group" varchar(5) NOT NULL, "rfid_uid" varchar(50) NOT NULL, "admission_number" varchar(50) NOT NULL, "is_active" boolean NOT NULL);
--
-- Create model StudentManagementUser
--
CREATE TABLE "student_management_studentmanagementuser" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "role" varchar(10) NOT NULL, "school_id" bigint NOT NULL);
CREATE TABLE "student_management_studentmanagementuser_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "studentmanagementuser_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "student_management_studentmanagementuser_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "studentmanagementuser_id" bigint NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model Event
--
CREATE TABLE "student_management_event" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(255) NOT NULL, "description" text NOT NULL, "date" date NOT NULL, "category" varchar(100) NOT NULL, "attachment_url" varchar(500) NULL, "class_limit_id" bigint NULL, "school_id" bigint NOT NULL);
--
-- Create model Exam
--
CREATE TABLE "student_management_exam" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "term" varchar(50) NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "classroom_id" bigint NOT NULL, "school_id" bigint NOT NULL);
--
-- Create model ReaderDevice
--
CREATE TABLE "student_management_readerdevice" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "device_type" varchar(10) NOT NULL, "location_description" varchar(255) NOT NULL, "status" varchar(10) NOT NULL, "last_seen" timestamp with time zone NULL, "firmware_version" varchar(50) NULL, "node_id" bigint NOT NULL, "school_id" bigint NOT NULL);
--
-- Create model Parent
--
CREATE TABLE "student_management_parent" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "first_name" varchar(100) NOT NULL, "last_name" varchar(100) NOT NULL, "relation" varchar(20) NOT NULL, "user_id" bigint NULL UNIQUE, "school_id" bigint NOT NULL);
--
-- Create model MessageThread
--
CREATE TABLE "student_management_messagethread" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "school_id" bigint NOT NULL);
--
-- Create model Message
--
CREATE TABLE "student_management_message" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "sender_id" varchar(50) NOT NULL, "message_text" text NOT NULL, "timestamp" timestamp with time zone NOT NULL, "attachment_url" varchar(500) NULL, "thread_id" bigint NOT NULL, "school_id" bigint NOT NULL);
--
-- Create model DeviceErrorLog
--
CREATE TABLE "student_management_deviceerrorlog" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "timestamp" timestamp with time zone NOT NULL, "error_message" text NOT NULL, "severity" varchar(10) NOT NULL, "device_id" bigint NULL, "school_id" bigint NOT NULL);
--
-- Add field school to collectornode
--
ALTER TABLE "student_management_collectornode" ADD COLUMN "school_id" bigint NOT NULL CONSTRAINT "student_management_c_school_id_bb643e88_fk_student_m" REFERENCES "student_management_school"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "student_management_c_school_id_bb643e88_fk_student_m" IMMEDIATE;
--
-- Add field school to classroom
--
ALTER TABLE "student_management_classroom" ADD COLUMN "school_id" bigint NOT NULL CONSTRAINT "student_management_c_school_id_61a32821_fk_student_m" REFERENCES "student_management_school"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "student_management_c_school_id_61a32821_fk_student_m" IMMEDIATE;
--
-- Create model CanteenItem
--
CREATE TABLE "student_management_canteenitem" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "price" numeric(6, 2) NOT NULL, "is_active" boolean NOT NULL, "school_id" bigint NOT NULL);
--
-- Create model Book
--
CREATE TABLE "student_management_book" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(255) NOT NULL, "author" varchar(255) NOT NULL, "isbn" varchar(20) NULL, "category" varchar(100) NOT NULL, "rack" varchar(20) NOT NULL, "copies_total" integer NOT NULL CHECK ("copies_total" >= 0), "copies_available" integer NOT NULL CHECK ("copies_available" >= 0), "school_id" bigint NOT NULL);
--
-- Create model Wallet
--
CREATE TABLE "student_management_wallet" ("student_id" bigint NOT NULL PRIMARY KEY, "balance" numeric(10, 2) NOT NULL, "updated_at" timestamp with time zone NOT NULL, "school_id" bigint NOT NULL);
--
-- Add field classroom to student
--
ALTER TABLE "student_management_student" ADD COLUMN "classroom_id" bigint NOT NULL CONSTRAINT "student_management_s_classroom_id_2bb049f3_fk_student_m" REFERENCES "student_management_classroom"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "student_management_s_classroom_id_2bb049f3_fk_student_m" IMMEDIATE;
--
-- Add field parent to student
--
ALTER TABLE "student_management_student" ADD COLUMN "parent_id" bigint NOT NULL CONSTRAINT "student_management_s_parent_id_de81d4e3_fk_student_m" REFERENCES "student_management_parent"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "student_management_s_parent_id_de81d4e3_fk_student_m" IMMEDIATE;
--
-- Add field school to student
--
ALTER TABLE "student_management_student" ADD COLUMN "school_id" bigint NOT NULL CONSTRAINT "student_management_s_school_id_56136c2a_fk_student_m" REFERENCES "student_management_school"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "student_management_s_school_id_56136c2a_fk_student_m" IMMEDIATE;
--
-- Add field user to student
--
ALTER TABLE "student_management_student" ADD COLUMN "user_id" bigint NULL UNIQUE CONSTRAINT "student_management_s_user_id_65e186a6_fk_student_m" REFERENCES "student_management_studentmanagementuser"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "student_management_s_user_id_65e186a6_fk_student_m" IMMEDIATE;
--
-- Add field student to messagethread
--
ALTER TABLE "student_management_messagethread" ADD COLUMN "student_id" bigint NOT NULL CONSTRAINT "student_management_m_student_id_17aeefd3_fk_student_m" REFERENCES "student_management_student"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "student_management_m_student_id_17aeefd3_fk_student_m" IMMEDIATE;
--
-- Create model BookIssue
--
CREATE TABLE "student_management_bookissue" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "issued_at" date NOT NULL, "due_date" date NOT NULL, "returned_at" date NULL, "fine_amount" numeric(6, 2) NOT NULL, "book_id" bigint NOT NULL, "school_id" bigint NOT NULL, "student_id" bigint NOT NULL);
--
-- Create model Subject
--
CREATE TABLE "student_management_subject" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "code" varchar(10) NOT NULL, "school_id" bigint NOT NULL);
--
-- Create model ExamSubject
--
CREATE TABLE "student_management_examsubject" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "max_marks" integer NOT NULL CHECK ("max_marks" >= 0), "exam_date" date NOT NULL, "exam_id" bigint NOT NULL, "school_id" bigint NOT NULL, "subject_id" bigint NOT NULL);
--
-- Create model TapLog
--
CREATE TABLE "student_management_taplog" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "rfid_uid" varchar(50) NOT NULL, "timestamp" timestamp with time zone NOT NULL, "device_id" varchar(100) NOT NULL, "direction" varchar(5) NOT NULL, "raw_data" jsonb NOT NULL, "school_id" bigint NOT NULL);
--
-- Create model Teacher
--
CREATE TABLE "student_management_teacher" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "first_name" varchar(100) NOT NULL, "last_name" varchar(100) NOT NULL, "subject_specialization" varchar(100) NOT NULL, "photo_url" varchar(200) NOT NULL, "is_active" boolean NOT NULL, "school_id" bigint NOT NULL, "user_id" bigint NULL UNIQUE);
--
-- Create model PracticeOutRecord
--
CREATE TABLE "student_management_practiceoutrecord" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date" date NOT NULL, "start_period" integer NOT NULL, "end_period" integer NOT NULL, "reason" varchar(255) NOT NULL, "school_id" bigint NOT NULL, "student_id" bigint NOT NULL, "approved_by_class_teacher_id" bigint NOT NULL, "requested_by_teacher_id" bigint NOT NULL);
--
-- Add field teacher to messagethread
--
ALTER TABLE "student_management_messagethread" ADD COLUMN "teacher_id" bigint NOT NULL CONSTRAINT "student_management_m_teacher_id_4b6754a4_fk_student_m" REFERENCES "student_management_teacher"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "student_management_m_teacher_id_4b6754a4_fk_student_m" IMMEDIATE;
--
-- Create model Homework
--
CREATE TABLE "student_management_homework" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "description" text NOT NULL, "due_date" timestamp with time zone NOT NULL, "attachment_url" varchar(500) NULL, "created_at" timestamp with time zone NOT NULL, "classroom_id" bigint NOT NULL, "school_id" bigint NOT NULL, "subject_id" bigint NOT NULL, "teacher_id" bigint NULL);
--
-- Add field class_teacher to classroom
--
ALTER TABLE "student_management_classroom" ADD COLUMN "class_teacher_id" bigint NULL CONSTRAINT "student_management_c_class_teacher_id_be3d05e2_fk_student_m" REFERENCES "student_management_teacher"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "student_management_c_class_teacher_id_be3d05e2_fk_student_m" IMMEDIATE;
--
-- Create model Announcement
--
CREATE TABLE "student_management_announcement" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(255) NOT NULL, "body" text NOT NULL, "scope" varchar(10) NOT NULL, "created_at" timestamp with time zone NOT NULL, "attachment_url" varchar(500) NULL, "classroom_id" bigint NULL, "school_id" bigint NOT NULL, "created_by_id" bigint NULL);
--
-- Alter unique_together for collectornode (1 constraint(s))
--
ALTER TABLE "student_management_collectornode" ADD CONSTRAINT "student_management_colle_school_id_mac_address_1c9e9ac7_uniq" UNIQUE ("school_id", "mac_address");
--
-- Create model AttendanceStatsDaily
--
CREATE TABLE "student_management_attendancestatsdaily" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date" date NOT NULL, "present_count" integer NOT NULL CHECK ("present_count" >= 0), "absent_count" integer NOT NULL CHECK ("absent_count" >= 0), "out_count" integer NOT NULL CHECK ("out_count" >= 0), "late_count" integer NOT NULL CHECK ("late_count" >= 0), "classroom_id" bigint NOT NULL, "school_id" bigint NOT NULL);
--
-- Create model WalletTransaction
--
CREATE TABLE "student_management_wallettransaction" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "timestamp" timestamp with time zone NOT NULL, "type" varchar(6) NOT NULL, "amount" numeric(10, 2) NOT NULL, "description" varchar(255) NULL, "item_id" bigint NULL, "school_id" bigint NOT NULL, "wallet_id" bigint NOT NULL);
--
-- Alter unique_together for student (2 constraint(s))
--
ALTER TABLE "student_management_student" ADD CONSTRAINT "student_management_stude_school_id_admission_numb_84d8d89b_uniq" UNIQUE ("school_id", "admission_number");
ALTER TABLE "student_management_student" ADD CONSTRAINT "student_management_student_school_id_rfid_uid_9695d142_uniq" UNIQUE ("school_id", "rfid_uid");
--
-- Create model MarkEntry
--
CREATE TABLE "student_management_markentry" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "marks_obtained" numeric(5, 2) NOT NULL, "remarks" text NULL, "exam_subject_id" bigint NOT NULL, "school_id" bigint NOT NULL, "student_id" bigint NOT NULL);
--
-- Create model HomeworkSubmission
--
CREATE TABLE "student_management_homeworksubmission" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "submitted_at" timestamp with time zone NOT NULL, "file_url" varchar(500) NULL, "remarks" text NULL, "homework_id" bigint NOT NULL, "school_id" bigint NOT NULL, "student_id" bigint NOT NULL);
--
-- Create model EventRegistration
--
CREATE TABLE "student_management_eventregistration" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "registered_at" timestamp with time zone NOT NULL, "status" varchar(10) NOT NULL, "event_id" bigint NOT NULL, "school_id" bigint NOT NULL, "student_id" bigint NOT NULL);
--
-- Create model Certificate
--
CREATE TABLE "student_management_certificate" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "certificate_url" varchar(500) NOT NULL, "generated_at" timestamp with time zone NOT NULL, "event_id" bigint NOT NULL, "school_id" bigint NOT NULL, "student_id" bigint NOT NULL);
--
-- Create model AttendanceRecord
--
CREATE TABLE "student_management_attendancerecord" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date" date NOT NULL, "period_number" integer NULL, "status" varchar(10) NOT NULL, "tap_timestamp" timestamp with time zone NULL, "source" varchar(10) NOT NULL, "verified_by_teacher" boolean NOT NULL, "school_id" bigint NOT NULL, "student_id" bigint NOT NULL);
--
-- Create model RFIDCard
--
CREATE TABLE "student_management_rfidcard" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "uid" varchar(20) NOT NULL, "issued_at" timestamp with time zone NOT NULL, "status" varchar(20) NOT NULL, "school_id" bigint NOT NULL, "assigned_to_student_id" bigint NULL, "assigned_to_teacher_id" bigint NULL);
--
-- Alter unique_together for messagethread (1 constraint(s))
--
ALTER TABLE "student_management_messagethread" ADD CONSTRAINT "student_management_messa_student_id_teacher_id_7bda7826_uniq" UNIQUE ("student_id", "teacher_id");
--
-- Alter unique_together for classroom (1 constraint(s))
--
ALTER TABLE "student_management_classroom" ADD CONSTRAINT "student_management_class_school_id_grade_section_dd874abd_uniq" UNIQUE ("school_id", "grade", "section");
--
-- Create model TeacherSubjectMapping
--
CREATE TABLE "student_management_teachersubjectmapping" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "is_active" boolean NOT NULL, "classroom_id" bigint NOT NULL, "school_id" bigint NOT NULL, "subject_id" bigint NOT NULL, "teacher_id" bigint NOT NULL);
--
-- Create model TimetableEntry
--
CREATE TABLE "student_management_timetableentry" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "day_of_week" integer NOT NULL, "period_number" integer NOT NULL, "start_time" time NOT NULL, "end_time" time NOT NULL, "room" varchar(10) NULL, "classroom_id" bigint NOT NULL, "school_id" bigint NOT NULL, "subject_id" bigint NOT NULL, "teacher_id" bigint NOT NULL);
CREATE INDEX "student_management_collectornode_mac_address_eeaa0198_like" ON "student_management_collectornode" ("mac_address" varchar_pattern_ops);
CREATE INDEX "student_management_school_name_6d02c35d_like" ON "student_management_school" ("name" varchar_pattern_ops);
CREATE INDEX "student_management_school_slug_41898f8c_like" ON "student_management_school" ("slug" varchar_pattern_ops);
CREATE INDEX "student_management_student_rfid_uid_ec468c4c" ON "student_management_student" ("rfid_uid");
CREATE INDEX "student_management_student_rfid_uid_ec468c4c_like" ON "student_management_student" ("rfid_uid" varchar_pattern_ops);
ALTER TABLE "student_management_studentmanagementuser" ADD CONSTRAINT "student_management_s_school_id_d4e07ff7_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_studentmanagementuser_email_31535aaf_like" ON "student_management_studentmanagementuser" ("email" varchar_pattern_ops);
CREATE INDEX "student_management_studentmanagementuser_school_id_d4e07ff7" ON "student_management_studentmanagementuser" ("school_id");
ALTER TABLE "student_management_studentmanagementuser_groups" ADD CONSTRAINT "student_management_stude_studentmanagementuser_id_d4f44fbe_uniq" UNIQUE ("studentmanagementuser_id", "group_id");
ALTER TABLE "student_management_studentmanagementuser_groups" ADD CONSTRAINT "student_management_s_studentmanagementuse_af823a81_fk_student_m" FOREIGN KEY ("studentmanagementuser_id") REFERENCES "student_management_studentmanagementuser" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_studentmanagementuser_groups" ADD CONSTRAINT "student_management_s_group_id_ead01f36_fk_auth_grou" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_student_studentmanagementuser_id_af823a81" ON "student_management_studentmanagementuser_groups" ("studentmanagementuser_id");
CREATE INDEX "student_management_student_group_id_ead01f36" ON "student_management_studentmanagementuser_groups" ("group_id");
ALTER TABLE "student_management_studentmanagementuser_user_permissions" ADD CONSTRAINT "student_management_stude_studentmanagementuser_id_6bac56e0_uniq" UNIQUE ("studentmanagementuser_id", "permission_id");
ALTER TABLE "student_management_studentmanagementuser_user_permissions" ADD CONSTRAINT "student_management_s_studentmanagementuse_5e51f579_fk_student_m" FOREIGN KEY ("studentmanagementuser_id") REFERENCES "student_management_studentmanagementuser" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_studentmanagementuser_user_permissions" ADD CONSTRAINT "student_management_s_permission_id_719ecd64_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_student_studentmanagementuser_id_5e51f579" ON "student_management_studentmanagementuser_user_permissions" ("studentmanagementuser_id");
CREATE INDEX "student_management_student_permission_id_719ecd64" ON "student_management_studentmanagementuser_user_permissions" ("permission_id");
ALTER TABLE "student_management_event" ADD CONSTRAINT "student_management_e_class_limit_id_df69943c_fk_student_m" FOREIGN KEY ("class_limit_id") REFERENCES "student_management_classroom" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_event" ADD CONSTRAINT "student_management_e_school_id_86a02973_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_event_class_limit_id_df69943c" ON "student_management_event" ("class_limit_id");
CREATE INDEX "student_management_event_school_id_86a02973" ON "student_management_event" ("school_id");
ALTER TABLE "student_management_exam" ADD CONSTRAINT "student_management_exam_school_id_name_classroom_59dafb86_uniq" UNIQUE ("school_id", "name", "classroom_id");
ALTER TABLE "student_management_exam" ADD CONSTRAINT "student_management_e_classroom_id_96cb0992_fk_student_m" FOREIGN KEY ("classroom_id") REFERENCES "student_management_classroom" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_exam" ADD CONSTRAINT "student_management_e_school_id_54bca09b_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_exam_classroom_id_96cb0992" ON "student_management_exam" ("classroom_id");
CREATE INDEX "student_management_exam_school_id_54bca09b" ON "student_management_exam" ("school_id");
ALTER TABLE "student_management_readerdevice" ADD CONSTRAINT "student_management_r_node_id_2eb4ecba_fk_student_m" FOREIGN KEY ("node_id") REFERENCES "student_management_collectornode" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_readerdevice" ADD CONSTRAINT "student_management_r_school_id_22051bac_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_readerdevice_node_id_2eb4ecba" ON "student_management_readerdevice" ("node_id");
CREATE INDEX "student_management_readerdevice_school_id_22051bac" ON "student_management_readerdevice" ("school_id");
ALTER TABLE "student_management_parent" ADD CONSTRAINT "student_management_p_user_id_871e801d_fk_student_m" FOREIGN KEY ("user_id") REFERENCES "student_management_studentmanagementuser" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_parent" ADD CONSTRAINT "student_management_p_school_id_a964b276_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_parent_school_id_a964b276" ON "student_management_parent" ("school_id");
ALTER TABLE "student_management_messagethread" ADD CONSTRAINT "student_management_m_school_id_5ccbd28c_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_messagethread_school_id_5ccbd28c" ON "student_management_messagethread" ("school_id");
ALTER TABLE "student_management_message" ADD CONSTRAINT "student_management_m_thread_id_3a3c8c2b_fk_student_m" FOREIGN KEY ("thread_id") REFERENCES "student_management_messagethread" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_message" ADD CONSTRAINT "student_management_m_school_id_32e2e800_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_message_thread_id_3a3c8c2b" ON "student_management_message" ("thread_id");
CREATE INDEX "student_management_message_school_id_32e2e800" ON "student_management_message" ("school_id");
ALTER TABLE "student_management_deviceerrorlog" ADD CONSTRAINT "student_management_d_device_id_fc4fc9f1_fk_student_m" FOREIGN KEY ("device_id") REFERENCES "student_management_readerdevice" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_deviceerrorlog" ADD CONSTRAINT "student_management_d_school_id_a42701dc_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_deviceerrorlog_device_id_fc4fc9f1" ON "student_management_deviceerrorlog" ("device_id");
CREATE INDEX "student_management_deviceerrorlog_school_id_a42701dc" ON "student_management_deviceerrorlog" ("school_id");
CREATE INDEX "student_management_collectornode_school_id_bb643e88" ON "student_management_collectornode" ("school_id");
CREATE INDEX "student_management_classroom_school_id_61a32821" ON "student_management_classroom" ("school_id");
ALTER TABLE "student_management_canteenitem" ADD CONSTRAINT "student_management_canteenitem_school_id_name_4341859b_uniq" UNIQUE ("school_id", "name");
ALTER TABLE "student_management_canteenitem" ADD CONSTRAINT "student_management_c_school_id_6177cc51_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_canteenitem_school_id_6177cc51" ON "student_management_canteenitem" ("school_id");
ALTER TABLE "student_management_book" ADD CONSTRAINT "student_management_book_school_id_isbn_70c134f4_uniq" UNIQUE ("school_id", "isbn");
ALTER TABLE "student_management_book" ADD CONSTRAINT "student_management_b_school_id_12faa0ba_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_book_school_id_12faa0ba" ON "student_management_book" ("school_id");
ALTER TABLE "student_management_wallet" ADD CONSTRAINT "student_management_w_student_id_e7e45dc3_fk_student_m" FOREIGN KEY ("student_id") REFERENCES "student_management_student" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_wallet" ADD CONSTRAINT "student_management_w_school_id_68fc5bdd_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_wallet_school_id_68fc5bdd" ON "student_management_wallet" ("school_id");
CREATE INDEX "student_management_student_classroom_id_2bb049f3" ON "student_management_student" ("classroom_id");
CREATE INDEX "student_management_student_parent_id_de81d4e3" ON "student_management_student" ("parent_id");
CREATE INDEX "student_management_student_school_id_56136c2a" ON "student_management_student" ("school_id");
CREATE INDEX "student_management_messagethread_student_id_17aeefd3" ON "student_management_messagethread" ("student_id");
ALTER TABLE "student_management_bookissue" ADD CONSTRAINT "student_management_b_book_id_74d73938_fk_student_m" FOREIGN KEY ("book_id") REFERENCES "student_management_book" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_bookissue" ADD CONSTRAINT "student_management_b_school_id_5d9f3048_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_bookissue" ADD CONSTRAINT "student_management_b_student_id_52c64588_fk_student_m" FOREIGN KEY ("student_id") REFERENCES "student_management_student" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_bookissue_book_id_74d73938" ON "student_management_bookissue" ("book_id");
CREATE INDEX "student_management_bookissue_school_id_5d9f3048" ON "student_management_bookissue" ("school_id");
CREATE INDEX "student_management_bookissue_student_id_52c64588" ON "student_management_bookissue" ("student_id");
ALTER TABLE "student_management_subject" ADD CONSTRAINT "student_management_subject_school_id_name_code_02e0a28e_uniq" UNIQUE ("school_id", "name", "code");
ALTER TABLE "student_management_subject" ADD CONSTRAINT "student_management_s_school_id_666f5c85_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_subject_school_id_666f5c85" ON "student_management_subject" ("school_id");
ALTER TABLE "student_management_examsubject" ADD CONSTRAINT "student_management_examsubject_exam_id_subject_id_1325841f_uniq" UNIQUE ("exam_id", "subject_id");
ALTER TABLE "student_management_examsubject" ADD CONSTRAINT "student_management_e_exam_id_d5ac5b76_fk_student_m" FOREIGN KEY ("exam_id") REFERENCES "student_management_exam" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_examsubject" ADD CONSTRAINT "student_management_e_school_id_c7b77bcc_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_examsubject" ADD CONSTRAINT "student_management_e_subject_id_c7292637_fk_student_m" FOREIGN KEY ("subject_id") REFERENCES "student_management_subject" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_examsubject_exam_id_d5ac5b76" ON "student_management_examsubject" ("exam_id");
CREATE INDEX "student_management_examsubject_school_id_c7b77bcc" ON "student_management_examsubject" ("school_id");
CREATE INDEX "student_management_examsubject_subject_id_c7292637" ON "student_management_examsubject" ("subject_id");
ALTER TABLE "student_management_taplog" ADD CONSTRAINT "student_management_t_school_id_63069a4e_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_taplog_rfid_uid_708ae5f0" ON "student_management_taplog" ("rfid_uid");
CREATE INDEX "student_management_taplog_rfid_uid_708ae5f0_like" ON "student_management_taplog" ("rfid_uid" varchar_pattern_ops);
CREATE INDEX "student_management_taplog_school_id_63069a4e" ON "student_management_taplog" ("school_id");
ALTER TABLE "student_management_teacher" ADD CONSTRAINT "student_management_t_school_id_1a9fde6c_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_teacher" ADD CONSTRAINT "student_management_t_user_id_a32a4739_fk_student_m" FOREIGN KEY ("user_id") REFERENCES "student_management_studentmanagementuser" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_teacher_school_id_1a9fde6c" ON "student_management_teacher" ("school_id");
ALTER TABLE "student_management_practiceoutrecord" ADD CONSTRAINT "student_management_p_school_id_1575208b_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_practiceoutrecord" ADD CONSTRAINT "student_management_p_student_id_5b2d7e1d_fk_student_m" FOREIGN KEY ("student_id") REFERENCES "student_management_student" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_practiceoutrecord" ADD CONSTRAINT "student_management_p_approved_by_class_te_5db9cfbc_fk_student_m" FOREIGN KEY ("approved_by_class_teacher_id") REFERENCES "student_management_teacher" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_practiceoutrecord" ADD CONSTRAINT "student_management_p_requested_by_teacher_675991f8_fk_student_m" FOREIGN KEY ("requested_by_teacher_id") REFERENCES "student_management_teacher" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_practiceoutrecord_school_id_1575208b" ON "student_management_practiceoutrecord" ("school_id");
CREATE INDEX "student_management_practiceoutrecord_student_id_5b2d7e1d" ON "student_management_practiceoutrecord" ("student_id");
CREATE INDEX "student_management_practic_approved_by_class_teacher__5db9cfbc" ON "student_management_practiceoutrecord" ("approved_by_class_teacher_id");
CREATE INDEX "student_management_practic_requested_by_teacher_id_675991f8" ON "student_management_practiceoutrecord" ("requested_by_teacher_id");
CREATE INDEX "student_management_messagethread_teacher_id_4b6754a4" ON "student_management_messagethread" ("teacher_id");
ALTER TABLE "student_management_homework" ADD CONSTRAINT "student_management_h_classroom_id_6d64f8b3_fk_student_m" FOREIGN KEY ("classroom_id") REFERENCES "student_management_classroom" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_homework" ADD CONSTRAINT "student_management_h_school_id_a5e9e3bd_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_homework" ADD CONSTRAINT "student_management_h_subject_id_280c0fb5_fk_student_m" FOREIGN KEY ("subject_id") REFERENCES "student_management_subject" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_homework" ADD CONSTRAINT "student_management_h_teacher_id_408df37b_fk_student_m" FOREIGN KEY ("teacher_id") REFERENCES "student_management_teacher" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_homework_classroom_id_6d64f8b3" ON "student_management_homework" ("classroom_id");
CREATE INDEX "student_management_homework_school_id_a5e9e3bd" ON "student_management_homework" ("school_id");
CREATE INDEX "student_management_homework_subject_id_280c0fb5" ON "student_management_homework" ("subject_id");
CREATE INDEX "student_management_homework_teacher_id_408df37b" ON "student_management_homework" ("teacher_id");
CREATE INDEX "student_management_classroom_class_teacher_id_be3d05e2" ON "student_management_classroom" ("class_teacher_id");
ALTER TABLE "student_management_announcement" ADD CONSTRAINT "student_management_a_classroom_id_6213e784_fk_student_m" FOREIGN KEY ("classroom_id") REFERENCES "student_management_classroom" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_announcement" ADD CONSTRAINT "student_management_a_school_id_dae67c01_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_announcement" ADD CONSTRAINT "student_management_a_created_by_id_214ae9c0_fk_student_m" FOREIGN KEY ("created_by_id") REFERENCES "student_management_teacher" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_announcement_classroom_id_6213e784" ON "student_management_announcement" ("classroom_id");
CREATE INDEX "student_management_announcement_school_id_dae67c01" ON "student_management_announcement" ("school_id");
CREATE INDEX "student_management_announcement_created_by_id_214ae9c0" ON "student_management_announcement" ("created_by_id");
ALTER TABLE "student_management_attendancestatsdaily" ADD CONSTRAINT "student_management_atten_school_id_date_classroom_b106909e_uniq" UNIQUE ("school_id", "date", "classroom_id");
ALTER TABLE "student_management_attendancestatsdaily" ADD CONSTRAINT "student_management_a_classroom_id_2e2d26b7_fk_student_m" FOREIGN KEY ("classroom_id") REFERENCES "student_management_classroom" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_attendancestatsdaily" ADD CONSTRAINT "student_management_a_school_id_46878e66_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_attendancestatsdaily_classroom_id_2e2d26b7" ON "student_management_attendancestatsdaily" ("classroom_id");
CREATE INDEX "student_management_attendancestatsdaily_school_id_46878e66" ON "student_management_attendancestatsdaily" ("school_id");
ALTER TABLE "student_management_wallettransaction" ADD CONSTRAINT "student_management_w_item_id_fda39a2d_fk_student_m" FOREIGN KEY ("item_id") REFERENCES "student_management_canteenitem" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_wallettransaction" ADD CONSTRAINT "student_management_w_school_id_76a37cae_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_wallettransaction" ADD CONSTRAINT "student_management_w_wallet_id_d12db7cc_fk_student_m" FOREIGN KEY ("wallet_id") REFERENCES "student_management_wallet" ("student_id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_wallettransaction_item_id_fda39a2d" ON "student_management_wallettransaction" ("item_id");
CREATE INDEX "student_management_wallettransaction_school_id_76a37cae" ON "student_management_wallettransaction" ("school_id");
CREATE INDEX "student_management_wallettransaction_wallet_id_d12db7cc" ON "student_management_wallettransaction" ("wallet_id");
ALTER TABLE "student_management_markentry" ADD CONSTRAINT "student_management_marke_exam_subject_id_student__0341a9d7_uniq" UNIQUE ("exam_subject_id", "student_id");
ALTER TABLE "student_management_markentry" ADD CONSTRAINT "student_management_m_exam_subject_id_d74025e6_fk_student_m" FOREIGN KEY ("exam_subject_id") REFERENCES "student_management_examsubject" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_markentry" ADD CONSTRAINT "student_management_m_school_id_17b0fc07_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_markentry" ADD CONSTRAINT "student_management_m_student_id_bf5625e4_fk_student_m" FOREIGN KEY ("student_id") REFERENCES "student_management_student" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_markentry_exam_subject_id_d74025e6" ON "student_management_markentry" ("exam_subject_id");
CREATE INDEX "student_management_markentry_school_id_17b0fc07" ON "student_management_markentry" ("school_id");
CREATE INDEX "student_management_markentry_student_id_bf5625e4" ON "student_management_markentry" ("student_id");
ALTER TABLE "student_management_homeworksubmission" ADD CONSTRAINT "student_management_homew_homework_id_student_id_7599c482_uniq" UNIQUE ("homework_id", "student_id");
ALTER TABLE "student_management_homeworksubmission" ADD CONSTRAINT "student_management_h_homework_id_536dc950_fk_student_m" FOREIGN KEY ("homework_id") REFERENCES "student_management_homework" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_homeworksubmission" ADD CONSTRAINT "student_management_h_school_id_3ff7d7f5_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_homeworksubmission" ADD CONSTRAINT "student_management_h_student_id_cb39c8c5_fk_student_m" FOREIGN KEY ("student_id") REFERENCES "student_management_student" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_homeworksubmission_homework_id_536dc950" ON "student_management_homeworksubmission" ("homework_id");
CREATE INDEX "student_management_homeworksubmission_school_id_3ff7d7f5" ON "student_management_homeworksubmission" ("school_id");
CREATE INDEX "student_management_homeworksubmission_student_id_cb39c8c5" ON "student_management_homeworksubmission" ("student_id");
ALTER TABLE "student_management_eventregistration" ADD CONSTRAINT "student_management_event_event_id_student_id_b387c2a5_uniq" UNIQUE ("event_id", "student_id");
ALTER TABLE "student_management_eventregistration" ADD CONSTRAINT "student_management_e_event_id_ce3935e8_fk_student_m" FOREIGN KEY ("event_id") REFERENCES "student_management_event" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_eventregistration" ADD CONSTRAINT "student_management_e_school_id_7b5f55d1_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_eventregistration" ADD CONSTRAINT "student_management_e_student_id_21c101a0_fk_student_m" FOREIGN KEY ("student_id") REFERENCES "student_management_student" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_eventregistration_event_id_ce3935e8" ON "student_management_eventregistration" ("event_id");
CREATE INDEX "student_management_eventregistration_school_id_7b5f55d1" ON "student_management_eventregistration" ("school_id");
CREATE INDEX "student_management_eventregistration_student_id_21c101a0" ON "student_management_eventregistration" ("student_id");
ALTER TABLE "student_management_certificate" ADD CONSTRAINT "student_management_certi_event_id_student_id_5b344b58_uniq" UNIQUE ("event_id", "student_id");
ALTER TABLE "student_management_certificate" ADD CONSTRAINT "student_management_c_event_id_8490a419_fk_student_m" FOREIGN KEY ("event_id") REFERENCES "student_management_event" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_certificate" ADD CONSTRAINT "student_management_c_school_id_4fcbca7e_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_certificate" ADD CONSTRAINT "student_management_c_student_id_5a12b759_fk_student_m" FOREIGN KEY ("student_id") REFERENCES "student_management_student" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_certificate_event_id_8490a419" ON "student_management_certificate" ("event_id");
CREATE INDEX "student_management_certificate_school_id_4fcbca7e" ON "student_management_certificate" ("school_id");
CREATE INDEX "student_management_certificate_student_id_5a12b759" ON "student_management_certificate" ("student_id");
ALTER TABLE "student_management_attendancerecord" ADD CONSTRAINT "student_management_atten_student_id_date_period_n_501e7179_uniq" UNIQUE ("student_id", "date", "period_number");
ALTER TABLE "student_management_attendancerecord" ADD CONSTRAINT "student_management_a_school_id_cc33bc47_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_attendancerecord" ADD CONSTRAINT "student_management_a_student_id_85d91284_fk_student_m" FOREIGN KEY ("student_id") REFERENCES "student_management_student" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_attendancerecord_date_96450571" ON "student_management_attendancerecord" ("date");
CREATE INDEX "student_management_attendancerecord_school_id_cc33bc47" ON "student_management_attendancerecord" ("school_id");
CREATE INDEX "student_management_attendancerecord_student_id_85d91284" ON "student_management_attendancerecord" ("student_id");
ALTER TABLE "student_management_rfidcard" ADD CONSTRAINT "student_management_rfidcard_school_id_uid_4f0d5e4c_uniq" UNIQUE ("school_id", "uid");
ALTER TABLE "student_management_rfidcard" ADD CONSTRAINT "student_management_r_school_id_98845b0b_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_rfidcard" ADD CONSTRAINT "student_management_r_assigned_to_student__d998eebc_fk_student_m" FOREIGN KEY ("assigned_to_student_id") REFERENCES "student_management_student" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_rfidcard" ADD CONSTRAINT "student_management_r_assigned_to_teacher__4bba64b4_fk_student_m" FOREIGN KEY ("assigned_to_teacher_id") REFERENCES "student_management_teacher" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_rfidcard_uid_89434e66" ON "student_management_rfidcard" ("uid");
CREATE INDEX "student_management_rfidcard_uid_89434e66_like" ON "student_management_rfidcard" ("uid" varchar_pattern_ops);
CREATE INDEX "student_management_rfidcard_school_id_98845b0b" ON "student_management_rfidcard" ("school_id");
CREATE INDEX "student_management_rfidcard_assigned_to_student_id_d998eebc" ON "student_management_rfidcard" ("assigned_to_student_id");
CREATE INDEX "student_management_rfidcard_assigned_to_teacher_id_4bba64b4" ON "student_management_rfidcard" ("assigned_to_teacher_id");
ALTER TABLE "student_management_teachersubjectmapping" ADD CONSTRAINT "student_management_teach_teacher_id_subject_id_cl_9b156696_uniq" UNIQUE ("teacher_id", "subject_id", "classroom_id");
ALTER TABLE "student_management_teachersubjectmapping" ADD CONSTRAINT "student_management_t_classroom_id_18babf97_fk_student_m" FOREIGN KEY ("classroom_id") REFERENCES "student_management_classroom" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_teachersubjectmapping" ADD CONSTRAINT "student_management_t_school_id_05d604ee_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_teachersubjectmapping" ADD CONSTRAINT "student_management_t_subject_id_f5c1844b_fk_student_m" FOREIGN KEY ("subject_id") REFERENCES "student_management_subject" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_teachersubjectmapping" ADD CONSTRAINT "student_management_t_teacher_id_0d645f7a_fk_student_m" FOREIGN KEY ("teacher_id") REFERENCES "student_management_teacher" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_teachersubjectmapping_classroom_id_18babf97" ON "student_management_teachersubjectmapping" ("classroom_id");
CREATE INDEX "student_management_teachersubjectmapping_school_id_05d604ee" ON "student_management_teachersubjectmapping" ("school_id");
CREATE INDEX "student_management_teachersubjectmapping_subject_id_f5c1844b" ON "student_management_teachersubjectmapping" ("subject_id");
CREATE INDEX "student_management_teachersubjectmapping_teacher_id_0d645f7a" ON "student_management_teachersubjectmapping" ("teacher_id");
ALTER TABLE "student_management_timetableentry" ADD CONSTRAINT "student_management_timet_classroom_id_day_of_week_ed06d565_uniq" UNIQUE ("classroom_id", "day_of_week", "period_number");
ALTER TABLE "student_management_timetableentry" ADD CONSTRAINT "student_management_t_classroom_id_65529159_fk_student_m" FOREIGN KEY ("classroom_id") REFERENCES "student_management_classroom" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_timetableentry" ADD CONSTRAINT "student_management_t_school_id_31d43f89_fk_student_m" FOREIGN KEY ("school_id") REFERENCES "student_management_school" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_timetableentry" ADD CONSTRAINT "student_management_t_subject_id_bca1ba77_fk_student_m" FOREIGN KEY ("subject_id") REFERENCES "student_management_subject" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "student_management_timetableentry" ADD CONSTRAINT "student_management_t_teacher_id_ef1136a1_fk_student_m" FOREIGN KEY ("teacher_id") REFERENCES "student_management_teacher" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "student_management_timetableentry_classroom_id_65529159" ON "student_management_timetableentry" ("classroom_id");
CREATE INDEX "student_management_timetableentry_school_id_31d43f89" ON "student_management_timetableentry" ("school_id");
CREATE INDEX "student_management_timetableentry_subject_id_bca1ba77" ON "student_management_timetableentry" ("subject_id");
CREATE INDEX "student_management_timetableentry_teacher_id_ef1136a1" ON "student_management_timetableentry" ("teacher_id");
COMMIT;
