# Generated by Django 5.0.14 on 2026-05-08 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
        ('sterling_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_threshold', models.TimeField(default='08:15')),
                ('grace_period', models.IntegerField(default=15)),
                ('theme_mode', models.CharField(choices=[('LIGHT', 'Light'), ('DARK', 'Dark')], default='LIGHT', max_length=10)),
                ('auto_notify_parents', models.BooleanField(default=False)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_config', to='sterling_core.unit')),
            ],
        ),
    ]
