# Generated by Django 5.0.14 on 2026-05-09 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_grade_subject_remove_eduprofile_grade_section_and_more'),
        ('sterling_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='sterling_core.unit'),
        ),
        migrations.AddField(
            model_name='section',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='sterling_core.unit'),
        ),
    ]
